name: Deploy

on: 
  push:
    branches:
      - master
      - dev

jobs:
  my-job:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      #获取代码
      - uses: actions/checkout@v2
      #给文件执行权限
      - name: chmod
        run: chmod +x decrypt_secret.sh
      #解密密钥
      - name: Decrypt large secret
        run: ./decrypt_secret.sh
        env:
          LARGE_SECRET_PASSPHRASE: ${{ secrets.GPG_KEY }}
      #安装npm
      - uses: actions/setup-node@v1
      #安装miniprogram-ci
      - name: install miniprogram-ci
        run: npm install -g miniprogram-ci
      #使用miniprogram-ci上传代码
      - name: upload
        run: miniprogram-ci upload --pp ./ --pkp $HOME/secrets/my_secret.key --appid wx807f40cbd0449570 --uv 1.1.8 -r 1 --enable-es6 true
      #--uv 版本号  -r ci机器人编号(1-30)  需要手动更改，同一个编号提交代码会覆盖
      # 版本号决定了小程序的版本，和开发者工具中的版本号意义一致。此处从1.1.7开始迭代
